In [2]:
import pandas as pd

df = pd.read_csv("StyleAdapterDataset_Final_Balanced.csv")

df.head()
print(df['label'].value_counts())


label
formal      40000
informal    40000
neutral     40000
Name: count, dtype: int64


In [3]:
from sklearn.model_selection import train_test_split

X = df["text"]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,        # %80 train – %20 test
    random_state=42,
    stratify=y            # sınıf dengesi korunsun
)

print("Train boyutu:", len(X_train))
print("Test  boyutu:", len(X_test))


Train boyutu: 96000
Test  boyutu: 24000


In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=30000,      # 30k kalsın
    ngram_range=(1, 3),      # 🔥 trigram eklendi
    stop_words=None
)

X_train_vec = tfidf.fit_transform(X_train)
X_test_vec  = tfidf.transform(X_test)

X_train_vec.shape, X_test_vec.shape


((96000, 30000), (24000, 30000))

In [5]:
%%time

from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

# ---------------------------------------------------------
# MODELLER (Optimize edilmiş hyperparametrelerle)
# ---------------------------------------------------------
models = {
    "Logistic Regression": LogisticRegression(
        max_iter=4000,
        C=2.0,          # regularization güçlendirildi
        n_jobs=-1
    ),

    "Linear SVM": LinearSVC(
        C=0.75          # SVM için daha iyi generalization
    ),

    "SGDClassifier": SGDClassifier(
        loss="hinge",   # Linear SVM ile aynı margin mantığı
        penalty="l2",
        alpha=1e-4,     # öğrenme hızını dengeler
        max_iter=5000,
        tol=1e-3
    ),

    "Naive Bayes": MultinomialNB()
}

# ---------------------------------------------------------
# MODEL EĞİTİM + TEST DÖNGÜSÜ
# ---------------------------------------------------------
results = {}

for name, model in models.items():
    print("="*70)
    print(f"📌 Training model: {name}")
    print("-"*70)

    # Model eğitimi
    model.fit(X_train_vec, y_train)

    # Tahmin
    pred = model.predict(X_test_vec)

    # Accuracy hesapla
    acc = accuracy_score(y_test, pred)
    results[name] = acc

    print(f"👉 Accuracy ({name}): {acc:.4f}\n")

    print("📊 Classification Report:")
    print(classification_report(y_test, pred))

    print("📉 Confusion Matrix:")
    print(confusion_matrix(y_test, pred))

    print("="*70, "\n\n")

# ---------------------------------------------------------
# EN İYİ MODELİ SEÇ
# ---------------------------------------------------------
best_model_name = max(results, key=results.get)
best_model = models[best_model_name]

print("🔥🔥🔥 BEST MODEL:", best_model_name, "→", results[best_model_name])


📌 Training model: Logistic Regression
----------------------------------------------------------------------
👉 Accuracy (Logistic Regression): 0.8147

📊 Classification Report:
              precision    recall  f1-score   support

      formal       0.99      0.99      0.99      8000
    informal       0.74      0.70      0.72      8000
     neutral       0.72      0.76      0.74      8000

    accuracy                           0.81     24000
   macro avg       0.82      0.81      0.81     24000
weighted avg       0.82      0.81      0.81     24000

📉 Confusion Matrix:
[[7902   43   55]
 [  43 5602 2355]
 [  53 1898 6049]]


📌 Training model: Linear SVM
----------------------------------------------------------------------
👉 Accuracy (Linear SVM): 0.8137

📊 Classification Report:
              precision    recall  f1-score   support

      formal       0.99      0.99      0.99      8000
    informal       0.74      0.70      0.72      8000
     neutral       0.71      0.76      0.73  

In [6]:
import pickle

with open("style_model.pkl", "wb") as f:
    pickle.dump(best_model, f)

with open("style_vectorizer.pkl", "wb") as f:
    pickle.dump(tfidf, f)
